image: playpauseandstop/docker-python:4.1.0-py39

stages:
  - lint
  - test

before_script:
  - make install

lint:
  stage: lint
  script:
    - make lint
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip-lint\]/
      allow_failure: true

test:
  stage: test
  script:
    - make test-only
